name: Sync on DOM Cloud
'on':
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_SGA }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_SGA }}
          data: >-
            {"commands":["git pull","npx pm2 restart all"]}
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_NYC }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_NYC }}
          data: >-
            {"commands":["git pull","npx pm2 restart all"]}
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_FRA }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_FRA }}
          data: >-
            {"commands":["git pull","npx pm2 restart all"]}
